version: '3.4'

services:
  eshopdb:
    image: postgres:16

  distributedcache:
    image: redis
    
  seq:
    image: datalust/seq:latest
    
  messagebus:
    image: rabbitmq:management
    
volumes:
  postgres_eshopdb: